977: dropdown option add
Gary-Community-Ventures/benefits-calculator pull request #1012
Opened 2024-04-09 14:56 UTC by Mdemenko1

## What (if any) features are you implementing?

Work for the issue #977. Adding an option to the dropdown in the question 5

![image](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/65931890/a6a52538-b4bd-4689-90b8-6a8e9b6a7fff)

2024-04-10 15:57 UTC, msrezaie requested changes
On the 'confirmation-page' if twice a month option is selected, the income is returned zero for annual like so:
<img width="761" alt="image" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/79583632/bd48042c-732d-4e6b-a6c3-bce46d1e3c99">

2024-04-10 15:57 UTC, msrezaie commented on src/Assets/frequencyOptions.tsx
> +  twiceMonth: <FormattedMessage id="frequencyOptions.twiceMonth" defaultMessage="twice a month" />,
The twice a month option in the backend is named `semimonthly`. Please name this the same in here as well.

2024-04-12 15:44 UTC, msrezaie approved these changes

2024-04-12 15:51 UTC, CalebPena approved these changes

2024-04-12 15:51 UTC, merged