Refactor/More Help page & Public Charge Rule link config
Gary-Community-Ventures/benefits-calculator pull request #1139
Opened 2024-06-14 00:43 UTC by msrezaie

What (if anything) did you refactor?
The following changes makes it possible to have NC specific values for some of the left out hardcoded values found throughout the frontend code base:
- Refactored hardcoded values found in the More Help page to consume values coming from the config as well as created translations labels for some of the hardcoded text in the page.
- Refactored a hardcoded link found in the Step 2 of the screener which links to the [Colorado Department of Human Services Public Charge Rule](https://cdhs.colorado.gov/public-charge-rule-and-colorado-immigrants#:~:text=About%20public%20charge&text=The%20test%20looks%20at%20whether,affidavit%20of%20support%20or%20contract.) to get its value from the config.

Any other comments, questions, or concerns?
The following translation labels need to be added through the Translations API admin in order to change the text found in the More Help page:
- moreHelp.resource_name
- moreHelp.resource_phone
- moreHelp.resource_FRCA-name
- moreHelp.resource_FRCA-description

2024-06-14 17:19 UTC, CalebPena commented
@msrezaie Could you change the base branch to `refactor/config-v2`

2024-06-14 17:41 UTC, msrezaie commented
@CalebPena you mean the changes from this PR to go to `refactor/config-v2` instead of `dev`, or change the branch that `refactor/left-out-hardcoded-values` is based on to `refactor/config-v2` instead of `refactor/frontend-config-to-backend`?

2024-06-14 17:59 UTC, CalebPena commented
> @CalebPena you mean the changes from this PR to go to `refactor/config-v2` instead of `dev`, or change the branch that `refactor/left-out-hardcoded-values` is based on to `refactor/config-v2` instead of `refactor/frontend-config-to-backend`?

Change the branch that `refactor/left-out-hardcoded-values` is based on to `refactor/config-v2` instead of `refactor/frontend-config-to-backend`

2024-06-14 18:23 UTC, msrezaie commented
@CalebPena ok, I was thinking to get rid of this PR and the branch, and create a new branch and base it off of the `refactor/config-v2` and create a new PR from the new branch. Would this be ok, or do you recommend a better approach for doing this?

2024-06-14 18:40 UTC, CalebPena commented
@msrezaie Feel free to create a new branch. You could also try rebasing this branch.

2024-07-16 16:37 UTC, CalebPena requested changes
@mexi-cano Can you review please. I think that some things that were removed previously got added back in this pr.

@msrezaie Can you make a backend pr to update the `add_config` script?

2024-07-16 16:37 UTC, CalebPena commented on src/Components/LandingPage/LandingPage.tsx
> +  const { public_charge_rule } = config ?? {};
```suggestion
  const acuteConditionOptions = useConfig('public_charge_rule');
```

2024-07-16 16:37 UTC, CalebPena commented on src/Components/MoreHelp/MoreHelp.tsx
> +  const { more_help } = config ?? {};
```suggestion
  const acuteConditionOptions = useConfig('more_help');
```

2024-07-16 16:37 UTC, CalebPena commented on src/Components/MoreHelp/MoreHelp.tsx
>    ];
This whole array should be added to the config.

2024-07-22 15:28 UTC, CalebPena requested changes

2024-07-22 15:28 UTC, CalebPena commented on src/Components/MoreHelp/MoreHelp.tsx
> +            <FormattedMessage id={resource.name.props.id} defaultMessage={resource.name.props.defaultMessage} />
```suggestion
            {resource.name}
```
The config transforms it into a formatted message, so you can just inline it.

2024-07-22 15:28 UTC, CalebPena commented on src/Components/MoreHelp/MoreHelp.tsx
> +              />
```suggestion
              {resource.description}
```

2024-07-22 15:28 UTC, CalebPena commented on src/Components/MoreHelp/MoreHelp.tsx
> +              <FormattedMessage id={resource.phone.props.id} defaultMessage={resource.phone.props.defaultMessage} />
```suggestion
              {resource.phone}
```

2024-07-24 16:37 UTC, CalebPena approved these changes
Looks good.

2024-07-24 16:37 UTC, merged