Refactor/household data
Gary-Community-Ventures/benefits-calculator pull request #1407
Opened 2024-12-18 17:01 UTC by ivonne-hernandez

What (if any) features are you implementing?
- Refactor the `householdData` components to use the new `HouseholdMemberForm` which utilizes `react-hook-form` to manage and validate state and `zod` for schema-based validation.

Were there any issues that arose?
- In regards to using the `MultiSelectTiles` component for the `healthInsurance` and `conditions` state I think that circumventing the `defaultValues` that we declare in each of these components is not a good practice. Once we find a solution for solving how these can be dynamically added to the `defaultValues`, as well our backend fields we can create a ticket to replace the current `RHFOptionCards` component with the `MultiSelectTiles`.

Is there anything that you need from your teammate?
- Please pull and test this branch to make sure that everything is working as intended.

2025-01-02 22:02 UTC, CalebPena requested changes
Good job on this PR. There are a couple of bugs that need to be fixed, and a couple of features that need to be readded. Additionally, there are a couple of comments because this pr is out of date with the changes in https://github.com/Gary-Community-Ventures/benefits-calculator/pull/1388. Then there are a bunch of optional style/refactor suggestions (some of which existed in the old household member component). I tried to make as many of the changes suggestions as possible. Also, feel free to make an issue if any of the suggestions will take too long.

2025-01-02 22:08 UTC, ivonne-hernandez commented on src/App.tsx
> +                    element={<HouseholdMemberForm key={window.location.href} />}
Yes, otherwise `react-hook-form` will just copy the information from the first household member over to all of them as they're generated since it doesn't have a unique key.

2025-01-03 16:45 UTC, ivonne-hernandez commented on src/Components/RHFComponents/RHFOptionCardGroup.tsx
Were there any issues that arose?

In regards to using the MultiSelectTiles component for the healthInsurance and conditions state I think that circumventing the defaultValues that we declare in each of these components is not a good practice. Once we find a solution for solving how these can be dynamically added to the defaultValues, as well our backend fields we can create a ticket to replace the current RHFOptionCards component with the MultiSelectTiles.

2025-01-03 17:11 UTC, ivonne-hernandez commented on src/Components/Steps/HouseholdMembers/HelperTextFunctions.tsx
@sydney-devine Can you please create a ticket to have us create a `HelperText` component and refactor all of the helper text functions that we currently have so that it's consistent?

2025-01-03 17:15 UTC, sydney-devine commented on src/Components/Steps/HouseholdMembers/HelperTextFunctions.tsx
@ivonne-hernandez will do

2025-01-03 17:16 UTC, ivonne-hernandez commented on src/Components/Steps/HouseholdMembers/HelperTextFunctions.tsx
Thank you!

2025-01-03 17:19 UTC, ivonne-hernandez commented on src/Components/Steps/HouseholdMembers/HHMSummaryCards.tsx
> +import './HHMSummaryCards.css';
@CalebPena Is this outdated? I merged the last released `dev` branch into this branch and am not experiencing any issues in terms of imports.

2025-01-03 17:20 UTC, ivonne-hernandez commented on src/Components/Steps/HouseholdMembers/HHMSummaryCards.tsx
> +    return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' }).format(num);
Yes.

2025-01-03 17:27 UTC, ivonne-hernandez commented on src/Components/Steps/HouseholdMembers/HHMSummaryCards.tsx
> +        <Box sx={{ marginBottom: '1.5rem' }}>
An article is more semantic.

2025-01-03 17:31 UTC, ivonne-hernandez commented on src/Components/Steps/SelectHelperFunctions/SelectHelperFunctions.tsx
@sydney-devine Can you please create a ticket to swap out the hard coded `createMenuItems` functions for all of our select components with this reusable one?

2025-01-03 19:01 UTC, ivonne-hernandez commented on src/Components/Steps/HouseholdMembers/HouseholdMemberForm.tsx
Member conditions should be saving now.

2025-01-03 19:24 UTC, ivonne-hernandez commented on src/Components/Steps/HouseholdMembers/HHMSummaryCards.tsx
> +    }
That doesn't work because the `relationshipToHH` is `undefined` not `headOfHousehold`.

2025-01-03 21:27 UTC, ivonne-hernandez commented on src/Components/Steps/HouseholdMembers/HHMSummaryCards.tsx
> +  ) => {
The `createMemberCard` function is only used in the `HHMSummaryCards` so I think it's fine to leave it in this file.

2025-01-06 22:30 UTC, CalebPena requested changes
@ivonne-hernandez If validation fails, then the screen should scroll to the top.

2025-01-09 17:26 UTC, ivonne-hernandez commented on src/Components/Steps/HouseholdMembers/HHMSummaryCards.tsx
> +  const createFormDataMemberCard = (
It's currently working as intended.

2025-01-09 17:35 UTC, ivonne-hernandez commented on src/Components/Steps/HouseholdMembers/HHMSummaryCards.tsx
> +  });
Thank you for this suggestion!

2025-01-09 18:15 UTC, ivonne-hernandez commented on src/Components/Steps/HouseholdMembers/HouseholdMemberForm.tsx
> +  const hasIncomeSchema = z.string().regex(/^true|false$/);
We use regex in other components so I think that it would be good to refactor all of them at the same time so that they're consistent throughout.

@sydney-devine can you please help me create a ticket to refactor some components who currently use regex to use zod unions instead?

2025-01-09 18:17 UTC, ivonne-hernandez commented on src/Components/Steps/HouseholdMembers/HouseholdMemberForm.tsx
> +        //TODO: make sure that this only shows up for the person at this index
No.

2025-01-10 21:58 UTC, merged

2025-01-13 19:49 UTC, ivonne-hernandez commented on src/Components/Steps/HouseholdMembers/HHMSummaryCards.tsx
> +            translateNumber(String(birthMonth).padStart(2, '0')) + '/' + translateNumber(birthYear)}
Yes. I just changed it.

2025-01-13 20:07 UTC, ivonne-hernandez commented on src/Components/Steps/HouseholdMembers/HouseholdMemberForm.tsx
> +  const CURRENT_YEAR = date.getFullYear();
Yes.

2025-01-13 20:22 UTC, ivonne-hernandez commented on src/Components/Steps/HouseholdMembers/HouseholdMemberForm.tsx
> +        message: 'Please select at least one health insurance option.',
This message is only used for internal debugging through react-hook-form:
<img width="1728" alt="Screenshot 2025-01-13 at 1 22 21 PM" src="https://github.com/user-attachments/assets/709bf6f7-374b-4553-b818-8d48554099bc" />

2025-01-13 20:44 UTC, ivonne-hernandez commented on src/Components/Steps/HouseholdMembers/HouseholdMemberForm.tsx
> +    birthYear: z
@sydney-devine Can you please help me create a ticket to add an error message in the event that the user selects a birthdate that is in the future?

2025-01-13 21:45 UTC, sydney-devine commented on src/Components/Steps/HouseholdMembers/HouseholdMemberForm.tsx
> +                    <FormHelperText sx={{ marginLeft: 0 }}>{renderBirthMonthHelperText()}</FormHelperText>
Sorry, idk what I'm looking at???

2025-01-13 21:52 UTC, ivonne-hernandez commented on src/Components/Steps/HouseholdMembers/HouseholdMemberForm.tsx
> +                    }}
Fixes a console error on the label

2025-01-13 22:23 UTC, ivonne-hernandez commented on src/Components/Steps/HouseholdMembers/HouseholdMemberForm.tsx
> +  };
This definitely is a good solution but I think that what we currently have is easier to understand.