Refactor/steps zero one
Gary-Community-Ventures/benefits-calculator pull request #611
Opened 2023-08-17 16:05 UTC by ivonne-hernandez

ClickUp Tickets: 
- https://app.clickup.com/t/8685bkz8a
- https://app.clickup.com/t/868546aen

What (if anything) did you refactor?
- I added `step-0` and `step-1`'s content to the `LandingPage`.
- I removed and added new bullet points and links
- I removed `step-0` routing and replaced it with `step-1`.
- I replaced the combined 2-1-1 & mfb logo.

New `step-1`:
<img width="1728" alt="Screenshot 2023-08-17 at 10 00 48 AM" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/86989161/a765f509-d63a-4caf-b778-f2c1e7445d74">
<img width="1727" alt="Screenshot 2023-08-17 at 10 00 29 AM" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/86989161/e0d6d653-6fb1-45a7-891e-392f33506402">

2023-08-17 20:09 UTC, CalebPena requested changes

2023-08-23 23:30 UTC, ivonne-hernandez commented on src/Components/LandingPage/LandingPage.js
> +  const [wasSubmitted, setWasSubmitted] = useState(false);
Yes, I used the errorController.

2023-08-25 16:07 UTC, CalebPena requested changes

2023-08-25 16:10 UTC, CalebPena approved these changes

2023-08-25 16:17 UTC, merged