Feat/table row dd icon
Gary-Community-Ventures/benefits-calculator pull request #628
Opened 2023-09-06 19:59 UTC by ivonne-hernandez

ClickUp Ticket: https://app.clickup.com/t/8685dq6pt

What (if anything) did you refactor?
- The toggle functionality that was handled by the `row.name` via a `Link` element has now been replaced with an `IconButton` at the end of each row. When you click on an initial `AddIcon` within a row, it will expand that row's children and the icon will transform into a `Remove` icon to indicate that the child element is collapsable. 

Were there any issues that arose?
-
Is there anything that you need from your teammate?
- Please review and let me know if you have any questions or concerns.

<img width="1728" alt="Screenshot 2023-09-06 at 1 53 28 PM" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/86989161/e5b2ed6e-ddcf-4576-bde8-684bbf173346">
<img width="1728" alt="Screenshot 2023-09-06 at 1 53 21 PM" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/86989161/99dfb0b6-8a12-4c62-b524-bb442112dd9e">
<img width="1728" alt="Screenshot 2023-09-06 at 1 49 49 PM" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/86989161/5e0bba7a-d4c3-4e07-9c52-3ce5ccb0c404">
<img width="1728" alt="Screenshot 2023-09-05 at 4 59 05 PM" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/86989161/8b02f55d-978a-4927-a4b9-902a0259bb6f">

2023-09-06 20:26 UTC, ivonne-hernandez commented on src/Components/Results/Results.js
> -
I moved these functions inside the `CustomDetailPanelToggle` component since `IconButton` will need them to handle these events accordingly.

2023-09-06 20:28 UTC, ivonne-hernandez commented on src/Components/Results/Results.js
> +      },
This is the toggle column that I added.

2023-09-06 20:31 UTC, ivonne-hernandez commented on src/Components/Results/Results.js
> +    };
This is the new `CustomDetailPanelToggle` component.

2023-09-08 15:04 UTC, CalebPena commented
I feel like the +/- looks a little awkward and is taking up a lot of space on the right side of the table.

2023-09-21 17:23 UTC, CalebPena requested changes

2023-09-21 17:23 UTC, CalebPena commented on src/Components/Results/Results.tsx
> +          <CustomDetailPanelToggle {...params} id={params.id} field={params.field} rowNode={params.rowNode} />
```suggestion
          <CustomDetailPanelToggle id={params.id} field={params.field} rowNode={params.rowNode} />
```

2023-09-21 17:23 UTC, CalebPena commented on src/Components/Results/Results.tsx
> +          <CustomDetailPanelToggle {...params} id={params.id} field={params.field} rowNode={params.rowNode} />
Or you can remove `id={params.id} field={params.field} rowNode={params.rowNode}`

2023-09-21 17:23 UTC, CalebPena commented on src/Components/Results/Results.tsx
> +        // @ts-ignore
What was the ts error here?

2023-09-21 22:24 UTC, CalebPena approved these changes

2023-09-22 16:12 UTC, merged