Feat/updated citizen filters
Gary-Community-Ventures/benefits-calculator pull request #650
Opened 2023-10-12 21:09 UTC by ivonne-hernandez

ClickUp Ticket: https://app.clickup.com/t/8685hm83u

What (if any) features are you implementing?
- I updated the citizenship filters such that when a user clicks on the `green_card` option, all of the four `green_card` subcategories appear checked. When a user deselects the `green_card` option, the subcategories disappear and are also deselected. 

Were there any issues that arose?
- No. The dollar value was changing accurately as expected.

Is there anything that you need from your teammate?
- Please check out this branch and test the new feature as much as possible and let me know if you have any questions or concerns.

2023-10-12 21:41 UTC, ivonne-hernandez commented on src/Assets/citizenshipFilterFormControlLabels.tsx
> +      defaultMessage="Individuals without citizenship or lawful U.S. presence"
This will require adding the requested text changes in our new translations UI via api/translations/admin.

2023-10-12 21:41 UTC, ivonne-hernandez commented on src/Assets/citizenshipFilterFormControlLabels.tsx
> +  green_card: <FormattedMessage id="citizenshipFCtrlLabel-green_card" defaultMessage="Green card holders" />,
This will require adding the requested text changes in our new translations UI via api/translations/admin

2023-10-12 21:41 UTC, ivonne-hernandez commented on src/Assets/citizenshipFilterFormControlLabels.tsx
> +  gc_5plus: <FormattedMessage id="citizenshipFCtrlLabel-gc_5plus" defaultMessage="ONLY after 5+ years in the U.S." />,
This will require adding the requested text changes in our new translations UI via api/translations/admin

2023-10-12 21:41 UTC, ivonne-hernandez commented on src/Assets/citizenshipFilterFormControlLabels.tsx
> +      defaultMessage="18 or older without a 5-year waiting period"
This will require adding the requested text changes in our new translations UI via api/translations/admin.

2023-10-12 21:42 UTC, ivonne-hernandez commented on src/Assets/citizenshipFilterFormControlLabels.tsx
> +      defaultMessage="younger than 18 without a 5-year waiting period"
This will require adding the requested text changes in our new translations UI via api/translations/admin.

2023-10-12 21:42 UTC, ivonne-hernandez commented on src/Assets/citizenshipFilterFormControlLabels.tsx
> +      defaultMessage="for health care benefits - younger than 19 or pregnant without a 5-year waiting period"
This will require adding the requested text changes in our new translations UI via api/translations/admin.

2023-10-12 21:42 UTC, ivonne-hernandez commented on src/Assets/citizenshipFilterFormControlLabels.tsx
> +      defaultMessage="Refugees or asylees (special rules or waiting periods may apply)"
This will require adding the requested text changes in our new translations UI via api/translations/admin.

2023-10-12 21:42 UTC, ivonne-hernandez commented on src/Components/FilterSection/CitizenshipPopover.tsx
> +        <FormattedMessage id="citizenshipPopover.showBenefits" defaultMessage="Show benefits available to:" />
This will require adding the requested text changes in our new translations UI via api/translations/admin.

2023-10-12 21:43 UTC, CalebPena requested changes

2023-10-12 21:43 UTC, CalebPena commented on src/Components/FilterSection/CitizenshipPopover.tsx
> +          citizenshipType === 'gc_under19_pregnant_no5';
```suggestion
          ['gc_5plus', 'gc_18plus_no5', 'gc_under18_no5', 'gc_under19_pregnant_no5'].includes(citizenshipType);
```

2023-10-12 21:43 UTC, CalebPena commented on src/Components/FilterSection/CitizenshipPopover.tsx
> +
Could you map over all of the categories just not render the green card categories if green card is not selected. That would enable you to remove the long if statement.

2023-10-13 15:27 UTC, CalebPena commented on src/Components/FilterSection/CitizenshipPopover.tsx
> +
```suggestion
if (citizenshipFilters.greenCard && isGreenCardSubCitizenshipType) {
  return <></>;
}
```
Then you can remove the renderMainFilters function.

2023-10-13 17:41 UTC, CalebPena commented on src/Components/Results/Results.tsx
> +      if (typedFiltCategory.value === 'Child Care, Preschool, and Youth' && updatedTotalEligibleDollarValue > 8640) {
Can you use the preschool category variable here.

2023-10-13 17:41 UTC, CalebPena commented on src/Components/Results/Results.tsx
> +  const preschoolProgramCategory = 'Child Care, Preschool, and Youth';
It looks like you forgot to change this back.

2023-10-13 18:12 UTC, CalebPena approved these changes

2023-10-13 18:12 UTC, merged