Rebranding Step-6
Gary-Community-Ventures/benefits-calculator pull request #790
Opened 2023-12-05 22:28 UTC by myang1010

What (if any) features are you implementing?
- Updated step-6

Is there anything that you need from your teammate?
- This ticket doesn't change the "Add Another Expense" button style and background color. But add the "+" sign at the beginning of the button. We have another ticket to handle "Back" and "Continue" buttons, and "Add Another Expense" button can reuse the style from there.

Screenshots
- When "No" is selected by default.
><img width="1345" alt="Screenshot 2023-12-06 at 9 09 58 AM" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/29790405/2b55fd46-d75c-44b0-bdf8-c26c302f8eb6">

- When "Yes" is selected(Ignore the "Add Another Expense" button style for now. The "+" sign was added).
><img width="1308" alt="Screenshot 2023-12-06 at 9 11 34 AM" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/29790405/93cf9ee5-dab8-4235-8182-b19cae5fd3ea">

- When there're multiple expensed added, the background color changes alternatively between light lavender and white(Still ignore the "Add Another Expense" button style).
><img width="1068" alt="Screenshot 2023-12-06 at 9 12 10 AM" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/29790405/c2988bba-58ac-4542-8296-cce3ba822012">

2023-12-06 19:05 UTC, CalebPena requested changes

2023-12-06 19:05 UTC, CalebPena commented on src/Components/ExpenseBlock/ExpenseQuestion.js
> +      style={{ backgroundColor: index >= 1 && index % 2 !== 0 ? 'var(--light-lavender-background)' : '' }}
What do you think about conditionally adding a class for background color. Also, I don't think that you need the `index >= 1 &&`.
```suggestion
      style={{ backgroundColor: index % 2 !== 0 ? 'var(--light-lavender-background)' : '' }}
```

2023-12-06 19:05 UTC, CalebPena commented on src/Assets/styleController.ts
> +  lightLavenderBackground: string;
Can you use `--secondary-background-color` from [Marianna/734/typography-updates](https://github.com/Gary-Community-Ventures/benefits-calculator/tree/Marianna/734/typography-updates)

2023-12-06 19:20 UTC, sydney-devine commented
@myang1010 for the alternating light lavender background, can we have it start with the very first expense? So if "yes", the first expense section should already have the lavender background, instead of on the 2nd expense added. ie: white background on main yes/no question; then: lavender, white, lavender, white, etc. 

When there is a lavender background, the input boxes should still be white:

<img width="249" alt="image" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/60ba518a-7746-4da9-a7c0-5a8de7496c03">

For the "X" to close out an expense, I don't love that the button is right up against the border of the lavender. Can we give some padding above and to the right so that it floats inside the light lavender instead of cutting off the one corner of it?

2023-12-06 20:54 UTC, myang1010 commented on src/Components/ExpenseBlock/ExpenseBlock.js
> +        startIcon={<AddIcon sx={{ fontSize: 'medium !important', mr: '-8px' }} />}
Tried `inherit`, but the "+" looks pretty big to me. I guess the icon here is using different size unit? 

- current with `medium !important`
<img width="231" alt="Screenshot 2023-12-06 at 12 50 40 PM" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/29790405/a33116c7-d42f-4b69-b74c-2f197d1e9541">

- switch to `inherit`
<img width="239" alt="Screenshot 2023-12-06 at 12 51 18 PM" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/29790405/8f6b1f8a-49b3-4041-9d79-2e30b8434d9c">

2023-12-06 21:52 UTC, myang1010 commented on src/Components/ExpenseBlock/ExpenseBlock.js
> +        startIcon={<AddIcon sx={{ fontSize: 'medium !important', mr: '-8px' }} />}
Have to keep `!important` here. But switch to `-0.5rem` for `mr`.

2023-12-06 21:54 UTC, myang1010 commented
@sydney-devine Here's the screenshot for the latest change,
<img width="899" alt="Screenshot 2023-12-06 at 1 47 35 PM" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/29790405/5537ed05-8cfd-4fe9-a892-f8299c513233">

Please let me know what you think. Thanks.

2023-12-06 23:17 UTC, sydney-devine commented
> @sydney-devine Here's the screenshot for the latest change, <img alt="Screenshot 2023-12-06 at 1 47 35 PM" width="899" src="https://private-user-images.githubusercontent.com/29790405/288558567-5537ed05-8cfd-4fe9-a892-f8299c513233.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5MDQ3MTQsIm5iZiI6MTcwMTkwNDQxNCwicGF0aCI6Ii8yOTc5MDQwNS8yODg1NTg1NjctNTUzN2VkMDUtOGNmZC00ZmU5LWE4OTItZjgyOTljNTEzMjMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDIzMTMzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWViNmJhNzJlYjA3MzllMjZmMGVhZDFjZGZjMjQzNzg1YzFiNDg2YTFiNDBlODM3ODFlOTJjZTgzNjkzNDY4ZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wHSC5Q5FbLvuuhAt5oYdVrfR6a74Ogd7_RLcykWlKek">
> 
> Please let me know what you think. Thanks.

Thank you!!

Definitely step in the right direction. 

Hard to tell on my screen/from screenshot how much wiggle room we have on this, but any way to do a littl emore padding on the left with the lavender background? The first letter of the question is just hitting that edge and it looks a little awkward. 

![image](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/1bcc0e89-2538-4217-a76c-9de666109419)

In a similar vein, let's add a little more padding above the first question. However much we have underneath the input box for the amount will work on top too. Let's just make it symmetrical. 

![image](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/7e75d35e-b421-4a9a-abfd-ed67c4269866)

It looks like the "X" is pushing down the question itself instead of top aligning with the expense type.

![image](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/b8029218-0467-4009-acef-6ec407faed24)

2023-12-07 17:51 UTC, myang1010 commented
@sydney-devine , here's the update screenshot based upon our last review feedback,

Changes made,
1. add extra padding to the top and bottom of the first question
2. add padding to the left of each question, so the first letters won't hit the edge
3. reduced the gap between "Close" button and question header
4. keep question input boxes white

<img width="902" alt="Screenshot 2023-12-07 at 9 37 41 AM" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/29790405/8d67966c-4790-4598-82e9-3322b1d4c065">

Thanks

2023-12-08 21:17 UTC, CalebPena commented on src/Assets/styleController.ts
> +  const lavenderColor = '#ECDEED';
Referenced this [here](https://github.com/Gary-Community-Ventures/benefits-calculator/pull/791/files/6ccd6ea24e623d2ec9ad78e1007c469333487b5d#r1418129878), but could we add this to the style controller with a name that describes what it does.

2023-12-13 19:37 UTC, CalebPena approved these changes
Good to merge if @sydney-devine  thinks that it looks good visually.

2023-12-13 20:18 UTC, sydney-devine commented
> Good to merge if @sydney-devine thinks that it looks good visually.

Do we have an updated screenshot on this? I think we were going to make some updates so that it matches what Ivonne did to the income question

2023-12-13 20:46 UTC, myang1010 commented
> Do we have an updated screenshot on this? I think we were going to make some updates so that it matches what Ivonne did to the income question

@sydney-devine , here are the latest screenshots, 
<img width="950" alt="step6-a" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/29790405/51de674c-6c87-44e1-a1c4-1c2b3374e1f0">


<img width="927" alt="step6-b" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/29790405/fb7a02b1-f3c9-4d97-90ba-340693020fab">

2023-12-13 20:59 UTC, sydney-devine commented
> > Do we have an updated screenshot on this? I think we were going to make some updates so that it matches what Ivonne did to the income question
> 
> @sydney-devine , here are the latest screenshots, <img alt="step6-a" width="950" src="https://private-user-images.githubusercontent.com/29790405/290324468-51de674c-6c87-44e1-a1c4-1c2b3374e1f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MDE0MjMsIm5iZiI6MTcwMjUwMTEyMywicGF0aCI6Ii8yOTc5MDQwNS8yOTAzMjQ0NjgtNTFkZTY3NGMtNmM4Ny00NGUxLWExYzQtMWMyYjMzNzRlMWYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDIwNTg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU2MzI3MGEwNjVhOTUwNWY3YTU0NWRiN2FlYjM1MWRmNDc0YTEzNGQ0MDJmNDc1Y2JlZDdjNTg1YWU0MWIzNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kU-GRw9B5dyoQP53nOyMgcjvwtt-F2ed3c1Ho3SMW-M">
> 
> <img alt="step6-b" width="927" src="https://private-user-images.githubusercontent.com/29790405/290323936-fb7a02b1-f3c9-4d97-90ba-340693020fab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MDE0MjMsIm5iZiI6MTcwMjUwMTEyMywicGF0aCI6Ii8yOTc5MDQwNS8yOTAzMjM5MzYtZmI3YTAyYjEtZjNjOS00ZDk3LTkwYmEtMzQwNjkzMDIwZmFiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDIwNTg0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczYWQwZjU5NmQ4YTU0YTMxNjM1YmI2ZmYzYWJhODE5MzI1MTYyMjM2ZTJlMmIwY2Y2MjEzOTA1YzAzODBhZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XpeWOggn2ZQBgcbaGRjE4CGYGLuYSXPJ_L-A6b3Z_Fs">

Thanks @myang1010! Just one question, are you hovered over that Add another expense button in this screen?

2023-12-13 21:15 UTC, myang1010 commented
> Thanks @myang1010! Just one question, are you hovered over that Add another expense button in this screen?

Yes, just wanted to show that "+" button is there.

2023-12-13 21:24 UTC, sydney-devine commented
> > Thanks @myang1010! Just one question, are you hovered over that Add another expense button in this screen?
> 
> Yes, just wanted to show that "+" button is there.

Thanks! Can I just snag a screen of it unhovered?

2023-12-13 21:30 UTC, myang1010 commented
> Thanks! Can I just snag a screen of it unhovered?

<img width="729" alt="Screenshot 2023-12-13 at 1 27 46 PM" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/29790405/c38fbc63-37cf-47fa-a546-b9e9cd3bb740">

The PR for the back and continue buttons will set this `Add another expense button` and `Back` button to the same style.

2023-12-13 21:45 UTC, sydney-devine commented
> > Thanks! Can I just snag a screen of it unhovered?
> 
> <img alt="Screenshot 2023-12-13 at 1 27 46 PM" width="729" src="https://private-user-images.githubusercontent.com/29790405/290333149-c38fbc63-37cf-47fa-a546-b9e9cd3bb740.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI1MDQyMDgsIm5iZiI6MTcwMjUwMzkwOCwicGF0aCI6Ii8yOTc5MDQwNS8yOTAzMzMxNDktYzM4ZmJjNjMtMzdjZi00N2ZhLWE1NDYtYjllOWNkM2JiNzQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDIxNDUwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM3YjU5M2ZkZWFkYzNmZmI5ZWI0ZjgxODAxNjc4ZTQ1NDMzNGExZTY2ODFmYzE4YTI0MjlmNjk1ZTNmNTZjNjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wXIQHS0Qe_PXKB85jRvCMO4Wm-WP9SsuESYSB1-lCEc">
> The PR for the back and continue buttons will set this `Add another expense button` and `Back` button to the same style.

Got it - thanks! @CalebPena you can merge.

2023-12-14 17:21 UTC, merged