743: Step 7 font updates
Gary-Community-Ventures/benefits-calculator pull request #798
Opened 2023-12-07 19:30 UTC by Mdemenko1

## What (if any) features are you implementing?

Work for the issue [743](https://github.com/Gary-Community-Ventures/benefits-calculator/issues/743)

Updating fonts

![image](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/65931890/2773e278-aedd-4bdf-b7b9-0b710142c4ee)

2023-12-08 21:52 UTC, CalebPena requested changes
It looks like the `Roboto Slab` font is not properly imported, so it is showing the wrong font on the header.

2023-12-08 22:06 UTC, Mdemenko1 commented
> It looks like the `Roboto Slab` font is not properly imported, so it is showing the wrong font on the header.

@sydney-devine Please confirm the font

@CalebPena I think this is exactly how it should look like, based on this discussion https://github.com/Gary-Community-Ventures/benefits-calculator/issues/743

2023-12-11 18:00 UTC, sydney-devine commented
> > It looks like the `Roboto Slab` font is not properly imported, so it is showing the wrong font on the header.
> 
> @sydney-devine Please confirm the font
> 
> @CalebPena I think this is exactly how it should look like, based on this discussion #743

So, @CalebPena and @ivonne-hernandez were digging into this a little. It sounds like maybe the font wasn't properly imported. Robot Slab does indeed have the tails on the letters, but the tails should look a little blockier than what's showing in the screenshot above. 

Here's what it looks like based on the branding guide. 
![image](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/109622199/c1b59735-587a-493d-9676-e1ff180152c8)

2023-12-12 18:30 UTC, CalebPena requested changes

2023-12-12 18:30 UTC, CalebPena commented on public/index.html
> +      href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;700&family=Roboto:wght@300;400;500;700&family=Roboto+Slab:wght@700&display=swap"
The font still is not importing for me.
![image](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/62856626/6cc408c5-540c-459e-96d2-8116591bbcdb)
![image](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/62856626/08687916-2d34-4492-9dd2-3283d629e1c0)

2023-12-12 20:57 UTC, CalebPena approved these changes

2023-12-12 21:01 UTC, merged