689: Footer added
Gary-Community-Ventures/benefits-calculator pull request #837
Opened 2023-12-22 17:23 UTC by Mdemenko1

### What (if any) features are you implementing?

Work for the issue [689](https://github.com/Gary-Community-Ventures/benefits-calculator/issues/689)

Adding footer in midBlue

![image](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/65931890/ffdec8f4-fc92-48b5-b75c-2980a08add50)

2023-12-22 19:23 UTC, CalebPena requested changes
It looks like the footer is blocking the back and continue buttons. Could you make it so it is the last element on the screen, but also at the bottom of the page. [This article](https://www.freecodecamp.org/news/how-to-keep-your-footer-where-it-belongs-59c6aa05c59c/) might be helpful.

2023-12-22 19:23 UTC, CalebPena commented on src/Components/Footer/Footer.js
> +    <nav>
Can we use a `footer` element instead?

2024-01-10 03:15 UTC, Mdemenko1 commented
@sydney-devine 

Do we want to footer to stay on the page all the time or only see it when you are scrolling to the bottom of the page?

All the time
![image](https://github.com/Gary-Community-Ventures/benefits-calculator/assets/65931890/bba0f559-8eb8-4625-8ddd-f4b71243a177)



After scrolling

https://github.com/Gary-Community-Ventures/benefits-calculator/assets/65931890/e7b17e2a-ed9b-4f25-938d-c0a3bd85bae4

2024-01-10 23:43 UTC, CalebPena commented
@Mdemenko1 We want the footer to be at the bottom of the screen after scrolling, but we don't want it in the middle of the screen if the page is shorter.

2024-01-10 23:54 UTC, Mdemenko1 commented
> @Mdemenko1 We want the footer to be at the bottom of the screen after scrolling, but we don't want it in the middle of the screen if the page is shorter.

Current behavior, footer appears on the end of the page after scrolling


https://github.com/Gary-Community-Ventures/benefits-calculator/assets/65931890/b3f532f7-dd8e-4728-86cb-449ffc3e3dc3

2024-01-10 23:58 UTC, CalebPena commented
@Mdemenko1 Sorry for the confusion, we want the footer to be at the very bottom if the page does not take up the full screen, but if the page does take up the whole screen, then we want it to be at the bottom after scrolling. So in the video we showed, we would want the footer to be at the bottom of the screen the whole time.

2024-01-12 16:47 UTC, Mdemenko1 commented
@CalebPena please check out new update for the footer when you have a minute, thank you

2024-01-12 18:28 UTC, CalebPena commented
@Mdemenko1 [This article](https://www.freecodecamp.org/news/how-to-keep-your-footer-where-it-belongs-59c6aa05c59c/) explains what we want to do. There are 2 cases. If the content is shorter than the screen height, then we want the footer to be at the bottom of the page. If the content is longer than the screen height, then we want the footer to be after the content.

2024-01-16 16:09 UTC, sydney-devine commented
> @sydney-devine
> 
> Do we want to footer to stay on the page all the time or only see it when you are scrolling to the bottom of the page?
> 
> All the time ![image](https://private-user-images.githubusercontent.com/65931890/295431285-bba0f559-8eb8-4625-8ddd-f4b71243a177.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU0MjE2NDgsIm5iZiI6MTcwNTQyMTM0OCwicGF0aCI6Ii82NTkzMTg5MC8yOTU0MzEyODUtYmJhMGY1NTktOGViOC00NjI1LThkZGQtZjRiNzEyNDNhMTc3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE2VDE2MDkwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiNzA3OWIwMTEwMDAwMDgzYjUwNjcxNTNlYzE3MGE3YmRhNjhiMjQzODQxZDVhOGNjYWM1NTIwZmU3MmFhZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PyPPD3pF4phk715KXdO3DwTnawsFSD8ifmV7KkVloOg)
> 
> After scrolling
> 
>  Screenshare.-.2024-01-09.10_12_56.PM.mp4

@Mdemenko1 Only when you scroll to bottom of the page. Sorry for the delayed response from being out last week!

2024-01-18 16:42 UTC, CalebPena approved these changes
Good job on this. There are 2 lines of CSS that I think you can delete because they are not doing anything.

2024-01-18 16:42 UTC, CalebPena commented on src/App.css
> +  height: auto !important;
I don't think that you need this line unless there is an edge case that I am missing.

2024-01-18 16:42 UTC, CalebPena commented on src/App.css
> +  min-height: 100%;
This line is overridden by the next line.

2024-01-18 19:08 UTC, Mdemenko1 commented
@CalebPena, I think its ready for merging

2024-01-18 19:13 UTC, CalebPena approved these changes

2024-01-18 19:14 UTC, CalebPena commented
@Mdemenko1 Changing the branch to be merged into `dev`.

2024-01-18 19:14 UTC, merged