Rebrand/cit filters
Gary-Community-Ventures/benefits-calculator pull request #866
Opened 2024-01-18 20:41 UTC by ivonne-hernandez

What (if any) features are you implementing?
- I created a filter component that uses our own filter function.

What (if anything) did you refactor?
- I refactored the `CitizenLabels` type and added a `CitizenLabelOptions` type to resolve TS errors.

Were there any issues that arose?
- The `overflow: visible !important` css rule in the `Share` component was causing the `Popover` element to not be anchored to the `Citizenship` button and allow scrolling, so I removed it.

Screenshot of issue in Desktop:
<img width="1725" alt="Screenshot 2024-01-18 at 1 40 55 PM" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/86989161/21a1c387-8d13-4afc-a41b-b1808955fba2">
Screenshot of issue in Mobile:
<img width="381" alt="Screenshot 2024-01-18 at 1 39 49 PM" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/86989161/1bf5ed31-9f72-48df-960a-2bf5e6717dbd">

Screenshot of problem in `211`:
<img width="408" alt="Screenshot 2024-01-18 at 1 38 05 PM" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/86989161/ff173ee5-24b3-40c8-ad70-942008c6d21d">
<img width="1728" alt="Screenshot 2024-01-18 at 1 39 35 PM" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/86989161/226fbde1-0879-4696-8720-3a6f58955535">

Is there anything that you need from your teammate?
- Please review and let me know if you have any questions or concerns.

2024-01-19 19:04 UTC, CalebPena requested changes

2024-01-19 20:41 UTC, CalebPena approved these changes

2024-01-23 16:55 UTC, sydney-devine commented
@ivonne-hernandez Screenshots of the mobile views look off from what I'm seeing? Looks like there's a gap? 

Desktop screens look good. Confirming that the sub bullet checkboxes won't appear until the main one has been checked (green card for example) - so behaving like the filter currently does.

2024-01-24 22:12 UTC, CalebPena commented
> @ivonne-hernandez Screenshots of the mobile views look off from what I'm seeing? Looks like there's a gap?
> 
> Desktop screens look good. Confirming that the sub bullet checkboxes won't appear until the main one has been checked (green card for example) - so behaving like the filter currently does.

I think that was an example of a bug that she fixed.

2024-01-24 22:13 UTC, sydney-devine commented
> > @ivonne-hernandez Screenshots of the mobile views look off from what I'm seeing? Looks like there's a gap?
> > Desktop screens look good. Confirming that the sub bullet checkboxes won't appear until the main one has been checked (green card for example) - so behaving like the filter currently does.
> 
> I think that was an example of a bug that she fixed.

Can I get final screenshots pls?

2024-01-25 18:48 UTC, ivonne-hernandez commented
> > > @ivonne-hernandez Screenshots of the mobile views look off from what I'm seeing? Looks like there's a gap?
> > > Desktop screens look good. Confirming that the sub bullet checkboxes won't appear until the main one has been checked (green card for example) - so behaving like the filter currently does.
> > 
> > 
> > I think that was an example of a bug that she fixed.
> 
> Can I get final screenshots pls?

@sydney-devine here are the screenshots for mobile:
<img width="500" alt="Screenshot 2024-01-25 at 11 47 38 AM" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/86989161/156eedce-de2b-4948-b205-a4727ebc78d8">
<img width="469" alt="Screenshot 2024-01-25 at 11 47 23 AM" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/86989161/122699ca-166e-4430-ad0d-41f2444e10b3">

2024-01-25 21:12 UTC, ivonne-hernandez commented
@ivonne-hernandez Fix the height when all filters are selected

2024-01-26 22:04 UTC, CalebPena approved these changes

2024-01-26 22:04 UTC, CalebPena commented on src/Components/Results/Programs/Filter.css
> +  vertical-align: top;
I don't think you need this.
```suggestion
```

2024-01-26 22:04 UTC, CalebPena commented on src/Components/Confirmation/Confirmation.css
> +.edit-button:hover {
Do we want to merge this change before the redesign is done?

2024-02-01 20:09 UTC, mexi-cano approved these changes

2024-02-05 17:50 UTC, CalebPena commented
@ivonne-hernandez can you pull from the `feat/results_redesign` branch

2024-02-06 20:37 UTC, merged