create new catefory heading component
Gary-Community-Ventures/benefits-calculator pull request #868
Opened 2024-01-18 21:24 UTC by myang1010

What (if any) features are you implementing?
- Created `CategoryHeading` component with two props, `headingType` and `amount`.

2024-01-18 23:31 UTC, CalebPena requested changes

2024-01-18 23:31 UTC, CalebPena commented on src/Components/Results/Programs/Programs.tsx
> +            <CategoryHeading headingType={programs[0].category} amount="200"></CategoryHeading>
Amount is hard coded. @Mdemenko1 created a function to get the value by category in her pr.

2024-01-18 23:31 UTC, CalebPena commented on src/Components/Results/CategoryHeading/CategoryHeading.js
Can we make this file TypeScript.

2024-01-18 23:31 UTC, CalebPena commented on src/Components/Results/CategoryHeading/CategoryHeading.js
> +  Transportation: { icon: HealthCare }, // placeholder icon
@sydney-devine do we have the icon for transportation.

2024-01-18 23:31 UTC, CalebPena commented on src/Components/Results/Programs/Programs.tsx
> +            <CategoryHeading headingType={programs[0].category} amount="200"></CategoryHeading>
```suggestion
            <CategoryHeading headingType={programs[0].category} amount="200" />
```

2024-01-18 23:31 UTC, CalebPena commented on src/Components/Results/CategoryHeading/CategoryHeading.css
We want to put all of the CSS in the `Results.css` file.

2024-01-19 16:15 UTC, CalebPena approved these changes
Looks good. Will merge when we get the placeholder icon.

2024-01-19 16:15 UTC, CalebPena commented on src/Components/Results/CategoryHeading/CategoryHeading.tsx
> +};
```suggestion
const headingOptionsMappings: { [key: string]: React.ComponentType } = {
  'Housing and Utilities': Housing,
  'Food and Nutrition': Food,
  'Health Care': HealthCare,
  Transportation: HealthCare, // placeholder icon
};
```

2024-01-19 16:15 UTC, CalebPena commented on src/Components/Results/CategoryHeading/CategoryHeading.tsx
> +  const { icon: IconComponent } = headingOptionsMappings[headingType.default_message];
```suggestion
  const IconComponent = headingOptionsMappings[headingType.default_message];
```

2024-01-19 16:45 UTC, ivonne-hernandez commented on src/Assets/CategoryHeadingIcons/food.svg
What do you think about importing these icons from the `AcuteConditions` folder?

2024-01-19 16:46 UTC, ivonne-hernandez commented on src/Assets/CategoryHeadingIcons/healthcare.svg
What do you think about importing these icons from the `AcuteConditions` folder?

2024-01-19 16:48 UTC, ivonne-hernandez commented on src/Components/Results/CategoryHeading/CategoryHeading.tsx
> +  Transportation: { icon: HealthCare }, // placeholder icon
Do you still need the actual `Transportation` icon?

2024-01-19 17:41 UTC, myang1010 commented
Hi @ivonne-hernandez , thanks for the suggestion. I considered reusing icons, but they're scattered. I could only reuse the Food icon from `AcuteConditions`. HealthCare and Housing icons are in different places. I haven't found the Transportation icon in our app. I think it's better to keep all icons together, so I'll hold off the changes for those icons for now.

2024-01-19 18:00 UTC, sydney-devine commented
@ivonne-hernandez & @myang1010 See original issue details. I am waiting on our designer for the remainder of the icons that are missing. So transportation, child care, youth, education and (one other one I can't remember off top of head) are coming. I should have them today or early next week so we can swap those icons in where they're missing.

2024-01-19 20:58 UTC, CalebPena commented on src/Components/Results/CategoryHeading/CategoryHeading.tsx
> +  headingType: { default_message: string; label: string };
We have a `Translation` type for this in `Types/Results.ts`

2024-01-23 22:02 UTC, CalebPena approved these changes

2024-01-23 22:02 UTC, merged