Rebrand/top buttons
Gary-Community-Ventures/benefits-calculator pull request #881
Opened 2024-01-24 20:27 UTC by ivonne-hernandez

What (if any) features are you implementing?
- Add the `Back to screener` and `Save my results` buttons.

Desktop view:
<img width="1728" alt="Screenshot 2024-01-24 at 1 26 06 PM" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/86989161/34db2f83-c9f6-4763-90bd-04749254c0c5">

Mobile view:
<img width="558" alt="Screenshot 2024-01-24 at 1 26 34 PM" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/86989161/e6325f38-f27b-4b48-9d83-f8bddc358f95">

2024-01-24 20:55 UTC, CalebPena requested changes

2024-01-24 20:55 UTC, CalebPena commented on src/Components/EmailResults/EmailResults.tsx
Can we break off the logic from `handleTextFieldChange` and move it into this component. It is not clear what `handleTextFieldChange` does.

2024-01-24 20:55 UTC, CalebPena commented on src/Components/EmailResults/EmailResults.tsx
> +      inputLabel: intl.formatMessage({ id: inputLabelId }),
Why did you remove the default message?

2024-01-24 23:52 UTC, ivonne-hernandez commented on src/Components/EmailResults/EmailResults.tsx
This is a very big change that requires architecting a lot of stuff. I know one solution is to copy and paste the code from `App` but because we've already done that for the `HouseholdData` it is becoming more and more difficult to source which one of the `handleTextfieldChange` functions is actually running. If you feel very strongly about this what do you think about creating a ticket for it?

2024-01-26 21:04 UTC, CalebPena commented on src/Components/EmailResults/EmailResults.tsx
I will make an issue.

2024-01-26 21:10 UTC, CalebPena approved these changes

2024-01-26 21:19 UTC, sydney-devine requested changes
Padding on the buttons seem a little off? We can discuss in person if easier, but on the side with the text for both of them there seems to be less padding. can we center the icons/text so that we don't have uneven padding on the left/right of the buttons?

2024-01-30 20:07 UTC, ivonne-hernandez commented on src/Components/Results/Header/Header.tsx
> +const Buttons = ({ type, handleTextfieldChange }: ResultsHeaderProps) => {
@sydney-devine This page is the Results page. The back button on the Results page should take them back to the Confirmation page.

2024-01-30 20:15 UTC, ivonne-hernandez commented
> Padding on the buttons seem a little off? We can discuss in person if easier, but on the side with the text for both of them there seems to be less padding. can we center the icons/text so that we don't have uneven padding on the left/right of the buttons?

@sydney-devine Let me know if this works:
<img width="1441" alt="Screenshot 2024-01-30 at 1 01 34 PM" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/86989161/dec7b3b1-9019-40a5-abfe-4572bd6498f0">
<img width="520" alt="Screenshot 2024-01-30 at 1 15 17 PM" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/86989161/c8e01f45-0e87-435b-9aaa-d1bcf8b0d6f9">

2024-02-05 17:49 UTC, CalebPena commented
@sydney-devine can this be merged? @ivonne-hernandez can you pull from `feat/results_redesign`

2024-02-05 18:59 UTC, sydney-devine commented
> @sydney-devine can this be merged? @ivonne-hernandez can you pull from `feat/results_redesign`

Yea we're good on this

2024-02-06 21:25 UTC, merged