831: 2-1-1 Button
Gary-Community-Ventures/benefits-calculator pull request #913
Opened 2024-02-02 18:32 UTC by Mdemenko1

## What (if any) features are you implementing?

Work for the issue [831](https://github.com/Gary-Community-Ventures/benefits-calculator/issues/831) 
Created component for `More Help at 2-1-1`

https://github.com/Gary-Community-Ventures/benefits-calculator/assets/65931890/4d4d8a07-9aed-4d91-957f-7f6b64fbaeef

2024-02-02 18:43 UTC, sydney-devine commented
> ## What (if any) features are you implementing?
> Work for the issue [831](https://github.com/Gary-Community-Ventures/benefits-calculator/issues/831) Created component for `More Help at 2-1-1`
> 
>  Screenshare.-.2024-02-02.1_30_17.PM.mp4

Looks great!

2024-02-02 18:43 UTC, sydney-devine approved these changes
Visual looks great on my end.

2024-02-02 22:01 UTC, CalebPena requested changes

2024-02-05 17:52 UTC, CalebPena approved these changes
Looks good.

2024-02-05 17:53 UTC, merged