Feat/new benefit flag
Gary-Community-Ventures/benefits-calculator pull request #927
Opened 2024-02-07 16:44 UTC by ivonne-hernandez

What (if any) features are you implementing?
- Add a `New Benefit` flag to the `ProgramCard`.

What (if anything) did you refactor?
- I refactored the styles for the `Can't find what you need` text by removing the `important` value and adding `display:flex`.
- I moved the `result-program` styles into their own file.

Is there anything that you need from your teammate?
- Please review and let me know if you have any questions or concerns.

Desktop view of the `New Benefit` flag:
<img width="1728" alt="Screenshot 2024-02-07 at 9 37 49 AM" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/86989161/d007ba8d-f2fc-46ff-949a-46fda70148f7">

Mobile view of the `New Benefit` flag:
<img width="440" alt="Screenshot 2024-02-07 at 9 37 35 AM" src="https://github.com/Gary-Community-Ventures/benefits-calculator/assets/86989161/243d6860-8b5c-4015-a322-2e71fa6f1c9e">

2024-02-07 18:40 UTC, CalebPena approved these changes
This is great. I just have one question about changing the 211 button back to a button.

2024-02-07 18:40 UTC, CalebPena commented on src/Components/Results/211Button/211Button.tsx
> +      <button className="hover-button">
This might be fixed by pulling from `feat/result_redesign`, but can you make this back into a `div`

2024-02-07 19:31 UTC, sydney-devine requested changes
Let's make the font/flag slightly bigger. Worried it won't be super legible as is.

2024-02-12 17:27 UTC, myang1010 approved these changes
Looks good! It's more logical for ProgramCard to have its own CSS class.

2024-02-16 16:32 UTC, sydney-devine approved these changes

2024-02-16 16:49 UTC, merged